import Card_Habilidades from "./Card_Habilidades";

export default function Habilidades() {
  return (
    <section className="container_habilidades">
      <Card_Habilidades
        nombreH={"HTML"}
        urlH={"https://www.vectorlogo.zone/logos/w3_html5/w3_html5-icon.svg"}
      />

      <Card_Habilidades
        nombreH={"CSS"}
        urlH={"https://www.vectorlogo.zone/logos/w3_css/w3_css-icon~old.svg"}
      />
      <Card_Habilidades
        nombreH={"JavaScript"}
        urlH={
          "https://www.vectorlogo.zone/logos/javascript/javascript-icon.svg"
        }
      />
      <Card_Habilidades
        nombreH={"Astro"}
        urlH={"https://svgl.app/library/astro.svg"}
      />
      <Card_Habilidades
        nombreH={"React"}
        urlH={"https://www.vectorlogo.zone/logos/reactjs/reactjs-icon.svg"}
      />
      <Card_Habilidades
        nombreH={"PHP"}
        urlH={"https://www.vectorlogo.zone/logos/php/php-icon.svg"}
      />
      <Card_Habilidades
        nombreH={"laravel"}
        urlH={"https://www.vectorlogo.zone/logos/laravel/laravel-icon.svg"}
      />
      <Card_Habilidades
        nombreH={"Boostrap"}
        urlH={
          "https://www.vectorlogo.zone/logos/getbootstrap/getbootstrap-icon.svg"
        }
      />
      <Card_Habilidades
        nombreH={"Tailwind"}
        urlH={
          "https://www.vectorlogo.zone/logos/tailwindcss/tailwindcss-icon.svg"
        }
      />
      <Card_Habilidades
        nombreH={"Mysql"}
        urlH={"https://www.vectorlogo.zone/logos/mysql/mysql-icon.svg"}
      />
      <Card_Habilidades
        nombreH={"TypeScript"}
        urlH={
          "https://www.vectorlogo.zone/logos/typescriptlang/typescriptlang-icon.svg"
        }
      />
      <Card_Habilidades
        nombreH={"Git"}
        urlH={"https://www.vectorlogo.zone/logos/git-scm/git-scm-icon.svg"}
      />
      <Card_Habilidades
        nombreH={"Postman"}
        urlH={
          "https://www.vectorlogo.zone/logos/getpostman/getpostman-icon.svg"
        }
      />
    </section>
  );
}
